import sys

import pygame

# ────────────────────────────────────────────────────────────
# CONSTANTS
# ────────────────────────────────────────────────────────────
TILE_SIZE = 16
PADDING = 1  # 1px padding in tileset
map_WIDTH = 40
map_HEIGHT = 40
SCREEN_WIDTH = TILE_SIZE * map_WIDTH
SCREEN_HEIGHT = TILE_SIZE * map_HEIGHT
FPS = 60

TOOL_TERRAIN = 0
TOOL_DECOR = 1
current_tool = TOOL_TERRAIN
selected_tile_index = 0


GRASS = 0
GRASS_DOT = 1
GRASS_PATCHY = 2
GRASS_FULL = 3
GRASS_FULL = 4

CLIFF_TL = 5
CLIFF_TR = 6
CLIFF_BL = 7
CLIFF_BR = 8
CLIFF_IN_TL = 9
CLIFF_IN_TR = 10
CLIFF_IN_BL = 11
CLIFF_IN_BR = 12

WATER_TL = 13
WATER_TR = 14
WATER_BL = 15
WATER_BR = 16
WATER_LILY = 17
WATER_CENTER = 18
WATER_BOTTOM = 19


DEC_TREE_SMALL = 0
DEC_TREE_STUMP_LEFT = 1
DEC_TREE_STUMP_RIGHT = 2
DEC_MUSHROOM_RED1 = 3
DEC_MUSHROOM_RED2 = 4
DEC_LOG_HORIZONTAL = 5
DEC_REED_SMALL = 6
DEC_REED_MEDIUM = 7
DEC_REED_TALL = 8
DEC_ROCK_SMALL = 9
DEC_ROCK_MEDIUM = 10
DEC_ROCK_BIG = 11
DEC_TREE_BIG_TL = 12  # part of large tree (top‑left)
DEC_TREE_BIG_TR = 13
DEC_TREE_BIG_BL = 14
DEC_TREE_BIG_BR = 15
DEC_TREE_PINE_TOP = 16
DEC_TREE_PINE_MID = 17
DEC_TREE_PINE_BASE = 18

DECOR_NAMES = {
    0: "TREE_SMALL",
    1: "TREE_STUMP_L",
    2: "TREE_STUMP_R",
    3: "MUSHROOM_RED1",
    4: "MUSHROOM_RED2",
    5: "LOG_HORZ",
    6: "REED_S",
    7: "REED_M",
    8: "REED_L",
    9: "ROCK_S",
    10: "ROCK_M",
    11: "ROCK_L",
    12: "TREE_BIG_TL",
    13: "TREE_BIG_TR",
    14: "TREE_BIG_BL",
    15: "TREE_BIG_BR",
    16: "TREE_PINE_TOP",
    17: "TREE_PINE_MID",
    18: "TREE_PINE_BASE",
    # add more if you define them above
}


# ────────────────────────────────────────────────────────────
# INITIALISE PYGAME
# ────────────────────────────────────────────────────────────
pygame.init()
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Forest Tileset Demo – Terrain + Decorations")
clock = pygame.time.Clock()

# ────────────────────────────────────────────────────────────
# LOAD GRAPHICS
# ────────────────────────────────────────────────────────────
tileset_img = pygame.image.load(
    "assets/TopDownFantasy-Forest/Tiles/Tileset.png"
).convert_alpha()

decor_img = pygame.image.load(
    "assets/TopDownFantasy-Forest/Decorations/Decorations.png"
).convert_alpha()


def draw_palette():
    pygame.draw.rect(screen, (30, 30, 30), (SCREEN_WIDTH - 100, 0, 100, SCREEN_HEIGHT))
    tile_list = tiles if current_tool == TOOL_TERRAIN else decorations
    for i, tile in enumerate(tile_list):
        x = SCREEN_WIDTH - 96 + (i % 2) * (TILE_SIZE + 4)
        y = 8 + (i // 2) * (TILE_SIZE + 4)
        screen.blit(tile, (x, y))
        if i == selected_tile_index:
            pygame.draw.rect(
                screen, (255, 255, 0), (x - 1, y - 1, TILE_SIZE + 2, TILE_SIZE + 2), 2
            )


def slice_padded_tileset(
    sheet: pygame.Surface, w: int, h: int, padding: int
) -> list[pygame.Surface]:
    tiles = []
    sw, sh = sheet.get_size()
    cols = (sw + padding) // (w + padding)
    rows = (sh + padding) // (h + padding)
    for row in range(rows):
        for col in range(cols):
            x = col * (w + padding)
            y = row * (h + padding)
            tiles.append(sheet.subsurface(pygame.Rect(x, y, w, h)))
    return tiles


def slice_sheet(sheet: pygame.Surface, w: int, h: int) -> list[pygame.Surface]:
    tiles = []
    sw, sh = sheet.get_size()
    for y in range(0, sh, h):
        for x in range(0, sw, w):
            tiles.append(sheet.subsurface(pygame.Rect(x, y, w, h)))
    return tiles


tiles = slice_padded_tileset(tileset_img, TILE_SIZE, TILE_SIZE, PADDING)
decorations = slice_sheet(decor_img, TILE_SIZE, TILE_SIZE)

# ────────────────────────────────────────────────────────────
# DATA ‑‑ TERRAIN & DECORATION mapS
# ────────────────────────────────────────────────────────────
map_layout = [
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
    [
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
        GRASS_FULL,
    ],
]


decor_map: list[list[int | None]] = [
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
    [None] * 40,
]


# ────────────────────────────────────────────────────────────
# DRAW HELPERS
# ────────────────────────────────────────────────────────────
def draw_map() -> None:
    for y, row in enumerate(map_layout):
        for x, tile_index in enumerate(row):
            if 0 <= tile_index < len(tiles):
                screen.blit(tiles[tile_index], (x * TILE_SIZE, y * TILE_SIZE))


def draw_decorations() -> None:
    for y, row in enumerate(decor_map):
        for x, deco_index in enumerate(row):
            if deco_index is not None and 0 <= deco_index < len(decorations):
                screen.blit(decorations[deco_index], (x * TILE_SIZE, y * TILE_SIZE))
                # If you ever need to debug which decoration is which, uncomment:
                # print(f"Placed {DECOR_NAMES.get(deco_index, deco_index)} at ({x},{y})")


print(len(decorations))
# ────────────────────────────────────────────────────────────
# MAIN LOOP
# ────────────────────────────────────────────────────────────
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_TAB:
                current_tool = (
                    TOOL_DECOR if current_tool == TOOL_TERRAIN else TOOL_TERRAIN
                )
                selected_tile_index = 0  # reset selection on switch

        elif event.type == pygame.MOUSEBUTTONDOWN:
            mx, my = pygame.mouse.get_pos()

            # Check if clicked inside palette
            if mx >= SCREEN_WIDTH - 100:
                tile_list = tiles if current_tool == TOOL_TERRAIN else decorations
                for i in range(len(tile_list)):
                    x = SCREEN_WIDTH - 96 + (i % 2) * (TILE_SIZE + 4)
                    y = 8 + (i // 2) * (TILE_SIZE + 4)
                    tile_rect = pygame.Rect(x, y, TILE_SIZE, TILE_SIZE)
                    if tile_rect.collidepoint(mx, my):
                        selected_tile_index = i
                        break
            else:
                # map click
                tx = mx // TILE_SIZE
                ty = my // TILE_SIZE
                if 0 <= tx < map_WIDTH and 0 <= ty < map_HEIGHT:
                    if event.button == 1:  # left click = place
                        if current_tool == TOOL_TERRAIN:
                            map_layout[ty][tx] = selected_tile_index
                        else:
                            decor_map[ty][tx] = selected_tile_index
                    elif event.button == 3:  # right click = erase
                        if current_tool == TOOL_TERRAIN:
                            map_layout[ty][tx] = GRASS  # or None
                        else:
                            decor_map[ty][tx] = None

        screen.fill((0, 0, 0))  # clear
        draw_map()
        draw_decorations()
        draw_palette()
        pygame.display.flip()
        clock.tick(FPS)

pygame.quit()
sys.exit()


"""
 [None, 145,146,147,148, None, None, None,10,11, None, None, 12,13, None, None,  None, None, None],
    [None, 161,162,163,164,None, None, None, 26,27,None, None, 28,29, None, None, None,  None, None, None],
    [None, 177,178,179,180,None, None, None, None, None, None, None, None, None,  None, None, None],
    [None, 193,194,195,196,None, None, None, None, None, 121,122, None, None, None,  None, None, None],
    [None, 209,210,211,66,67, None, None, None, None, None, 137,138,139, None, None, None, None, None],
    [None, 225,226,227,82,83,137,138,139,None, None, None, None, None, None, None, None, None,  None, None, None],

   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
    [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
    [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,None,66,67,68,69],
    [65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,None,82,83,84,85],
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96],
    [97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
    [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128],
    [129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144],
   [None, None, None, None, None, None, None, None, None, None, 0,  1,  2, None, None, None],
    [None, None, None, None, None, None, None, None, None, None, 0,  1,  2, None, None, None],
    [None, None, None, None, None, None, None, None, None, None, 0,  1,  2, None, None, None],

    [145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
    [161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
    [177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192],
    [193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208],
    [209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224],
    [225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240],
    [241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256],
    [None, None, 240, 241, 242, None, None, None, None, None, 0,  1,  2, None, None, None],
    [None, None, None, None, None, None, None, None, None, None, 0,  1,  2, None, None, None],
]
"""
